# Generated by Django 3.2.8 on 2021-10-11 23:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0002_alter_img_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
