# Generated by Django 3.2.8 on 2021-10-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_alter_img_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
